<?php

namespace App\Models;

use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Hidden;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Laravel\Sanctum\HasApiTokens;

#[Fillable([
    'name',
    'email',
    'password',
])]
#[Hidden([
    'password',
    'remember_token',
])]
class User extends Authenticatable
{
    /** @use HasFactory<UserFactory> */
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * Attributes that should be cast.
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | RBAC
    |--------------------------------------------------------------------------
    */

    /**
     * Roles assigned to the user.
     */
    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class);
    }

    /*
    |--------------------------------------------------------------------------
    | Reviews
    |--------------------------------------------------------------------------
    */

    /**
     * Software reviews created by the user.
     */
    public function softwareReviews(): HasMany
    {
        return $this->hasMany(
            SoftwareReview::class,
            'user_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Saved Software
    |--------------------------------------------------------------------------
    */

    /**
     * Software saved by the user.
     */
    public function savedSoftwares(): HasMany
    {
        return $this->hasMany(
            SavedSoftware::class,
            'user_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Comparison
    |--------------------------------------------------------------------------
    */

    /**
     * Comparison records created by the user.
     */
    public function comparisons(): HasMany
    {
        return $this->hasMany(
            Comparison::class,
            'user_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Recommendation
    |--------------------------------------------------------------------------
    */

    /**
     * Recommendation sessions created by the user.
     */
    public function recommendationSessions(): HasMany
    {
        return $this->hasMany(
            RecommendationSession::class,
            'user_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Implementation Leads
    |--------------------------------------------------------------------------
    */

    /**
     * Implementation requests created by the user.
     */
    public function implementationRequests(): HasMany
    {
        return $this->hasMany(
            ImplementationRequest::class,
            'user_id'
        );
    }

    /**
     * Implementation requests assigned to this user.
     */
    public function assignedImplementationRequests(): HasMany
    {
        return $this->hasMany(
            ImplementationRequest::class,
            'assigned_to'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Affiliate / Outbound Tracking
    |--------------------------------------------------------------------------
    */

    /**
     * Outbound clicks generated by the user.
     */
    public function outboundClicks(): HasMany
    {
        return $this->hasMany(
            OutboundClick::class,
            'user_id'
        );
    }

    /*
    |--------------------------------------------------------------------------
    | Audit
    |--------------------------------------------------------------------------
    */

    /**
     * Audit logs generated by the user.
     */
    public function auditLogs(): HasMany
    {
        return $this->hasMany(
            AuditLog::class,
            'user_id'
        );
    }
}
